<?php
$language['_noscript'] = 'The Cultural Heritage Map and documentary relies on various open source, free javascript libraries including Leaflet. We never get/store any information regarding your visit to the site. Please enable javascripts and try again.';
$language['page_title'] = 'Multi cultural Heritage of Anatolia by Hrant Dink Foundation';
$language['_count'] = 'number of buildings: ';
$language['_not_found'] = 'No such place/name in our database';
$language['_geo_error'] = 'Unable to retrieve your location';
$language['_find_me'] = 'Explore around';
$language['cookie'] = 'data policy';
// main menu
  $language['_about'] = 'About';
    $language['_about_map'] = 'Cultural Heritage Map';
    $language['_about_credits'] = 'Contributors';
    $language['_about_method'] = 'Methodology';
    $language['_about_biblio'] = 'Bibliography';

  $language['_about_manual'] = 'Manual';

  $language['_contact'] = 'Contact Us';
  $language['_contact_form'] = 'Contribute to map';

  $language['_share_facebook'] = 'Share this map on Facebook';
  $language['_share_twitter'] = 'Tweet this map';
  $language['_share_docu_facebook'] = 'Share this map on Facebook';
  $language['_share_docu_twitter'] = 'Tweet this map';

// search filters
  $language['_placeholder'] = 'Name, village, district, province...';
  $language['_city_label'] = 'limit search with a city';
  $language['_ethnicity_label'] = 'limit search with a community';
  $language['_denomination_label'] = 'limit search with a denomination';
  $language['_type_label'] = 'limit search with building type';
  $language['_search_button'] = 'Find';
  $language['_search_options'] = 'Toggle search filters';

// info page variables
  $language['_visuals'] = 'Photos';
  $language['_no_image'] = "Sorry we don't have any pictures of this structure.";
  $language['_noname'] = "Name unknown";
  $language['_bibliofn'] = "Bibliography";
  $language['_links'] = "For more information";
  $language['_registration'] = "Registration information";
  $language['_status'] = "Today used as";
  $language['_fw_title'] = "Fieldwork notes";
  $language['_fw_inspection'] = "Inspection date";

// map labels
 $language['_layer_map'] = "Map";
 $language['_layer_satellite'] = "Satellite";
 $language['_layer_documentary'] = "Field Stories";
 $language['_layer_cultural_heritage'] = "Inventoried Buildings";

 // tour variables
  $language['_prev'] = "previous";
  $language['_next'] = "next";
  $language['_tourlist'] = "list";

  // Mail form variables
  $language['mail_from'] = 'Your name';
  $language['mail_address'] = 'Your e-mail address';
  $language['mail_subject'] = 'Your subject';
  $language['mail_help'] = 'Please write the original function (church, monastery, chapel, hospital, orphanage, synagogue, school, or cemetery), ethno-religious community, and province of the building that you would like to add onto the map. Please also write, if known, the current and/or old names of the building, its district, and village or neighborhood; as well as the current use of the building, the date when it lost its original function, access to it and its ownership status. Please list the sources and links on the concerning the building. If you would like to send pictures, please send via email.';
  $language['mail_submit'] = 'Submit';
  $language['mail_sent'] = 'Thank you for your contribution! We will update our database as soon as we validate the information.';

?>
