<?php
$language['_noscript'] = 'Kültür Varlıkları Haritası ve Kültürel Miras belgeseli Leaflet ve başka birkaç özgür, açık kaynak kodlu javascript kitaplıklarını kullanıyor. Ziyaretinize dair hiçbir bilgiyi sunucuda saklamıyor, sizden herhangi bir bilgi almıyoruz. Lütfen javascript desteğini aktif hale getirerek tekrar deneyin.';
$language['page_title'] = 'Anadolu\'nun Çok Kültürlü Kültürel Mirası / Hrant Dink Vakfı';
$language['page_desc'] = 'Hrant Dink Vakfı, Kültürel Miras Araştırması, Türkiye Kültür Varlıkları etkileşimli haritası';
$language['_twitter'] = '@HrantDinkVakfi ';
$language['_count'] = 'yapı sayısı: ';
$language['_not_found'] = 'Aranan isimde yer/yapı bulunamadı';
$language['_geo_error'] = 'Konum bilgisi alınamadı';
$language['_find_me'] = 'Çevremi göster';
$language['cookie'] = 'veri politikamız';
// main menu
$language['_about'] = 'Hakkında';
  $language['_about_map'] = 'Kültür Varlıkları Haritası';
  $language['_about_credits'] = 'Katkıda Bulunanlar';
  $language['_about_method'] = 'Yöntembilim';
  $language['_about_biblio'] = 'Kaynakça';

$language['_about_manual'] = 'Kılavuz';

$language['_contact'] = 'İletişim';
$language['_contact_form'] = 'Katkıda Bulunun';

  $language['_share_facebook'] = 'Bu haritayı Facebook hesabınızda paylaşın';
  $language['_share_twitter'] = 'Bu haritayı tweet atın';
  $language['_share_docu_facebook'] = 'Bu hikâyeyi Facebook hesabınızda paylaşın';
  $language['_share_docu_twitter'] = 'Bu hikâyeyi tweet atın';

// search filters
$language['_placeholder'] = 'Yapı, köy, il, ilçe adı...';
$language['_city_label'] = 'tek bir şehirde ara';
$language['_ethnicity_label'] = 'tek bir etnik topluluk ara';
$language['_denomination_label'] = 'tek bir mezhebi ara';
$language['_type_label'] = 'tek bir yapı cinsini ara';
$language['_search_button'] = 'Bul';
$language['_search_options'] = 'Arama filtrelerini göster';

// advanced search
  $language['_adv_search_title'] = 'Gelişmiş Arama';
  $language['_adv_city'] = 'Aramaya dahil etmek istediğiniz şehirleri seçin';
  $language['_adv_ethnicity'] = 'Hangi toplulukları dahil etmek istediğinizi seçin';
  $language['_adv_denomination'] = 'Hangi mezhepleri dahil etmek istediğinizi seçin';
  $language['_adv_type'] = 'Hangi tür yapıları dahil etmek istediğinizi seçin';

// info page variables
  $language['_visuals'] = 'Fotoğraflar';
  $language['_no_image'] = "Özür dileriz, bu yapıya ait fotoğrafa ulaşamadık.";
  $language['_noname'] = "Adı bilinmiyor";
  $language['_bibliofn'] = "Kaynakça";
  $language['_links'] = "Daha çok bilgi için";
  $language['_registration'] = "Tescil bilgisi";
  $language['_status'] = "Güncel kullanım";
  $language['_fw_title'] = "Saha araştırması notları";
  $language['_fw_inspection'] = "Ziyaret tarihi";

  // map labels
   $language['_layer_map'] = "Harita";
   $language['_layer_satellite'] = "Uydu Görüntüsü";
   $language['_layer_documentary'] = "Saha Hikâyeleri";
   $language['_layer_cultural_heritage'] = "Envanter Yapıları";

  // tour variables
   $language['_prev'] = "önceki";
   $language['_next'] = "sonraki";
   $language['_tourlist'] = "liste";

  // Mail form variables
  $language['mail_from'] = 'İsminiz?';
  $language['mail_address'] = 'E-posta adresiniz?';
  $language['mail_subject'] = 'Hangi konuda yazıyorsunuz?';
  $language['mail_help'] = 'Lütfen haritaya eklemek istediğiniz yapının özgün işlevi (kilise, manastır, şapel, hastane, yetimhane, sinagog, okul veya mezarlık), ait olduğu etnik-dinî topluluk ve bulunduğu ili yazınız. Ayrıca, biliyorsanız, yapının, ilçesinin, ve köy veya mahallesinin güncel ve/veya eski adlarını; yapının güncel kullanımını, yapım ve işlevini kaybetme tarihini, ulaşım bilgilerini ve mülkiyet durumunu yazınız. Yapıya dair kaynak ve bağlantıları belirtiniz. Eğer fotoğraf göndermek istiyorsanız e-posta yoluyla ulaştırmanızı rica ederiz.';
  $language['mail_submit'] = 'Formu Gönder';
  $language['mail_sent'] = 'Katkınız için çok teşekkür ederiz! <br/>Veritabanımızı güncellemek üzere bilgileri değerlendireceğiz.';
?>
