          <h1 class="h2">Site Metinlerini Düzenle</h1>
        </div><div>
<div class="row">
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarToggler">
      <ul class="navbar-nav nav-fill ml-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="edit_static.php?page=_about_map">Kültür Varlıkları Haritası</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="edit_static.php?page=_about_credits">Katkıda Bulunanlar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="edit_static.php?page=_about_docu">Saha Hikâyeleri</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="edit_static.php?page=_about_manual">Yardım</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="edit_static.php?page=_research_method">Yöntembilim</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="edit_static.php?page=_research_biblio">Kaynakça</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="edit_static.php?page=_contact">İletişim</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="edit_static.php?page=_cookie_policy">Veri/Çerez Politikası</a>
          </li>
        </ul>
    </div>
  </nav>
</div>
